from OpenGL.GL import *


UNIFORM_TYPE_DICT = {
	int(GL_FLOAT) : (glUniform1fv, GL_FLOAT, 1, 'f4'), 
	int(GL_FLOAT_VEC2) : (glUniform2fv, GL_FLOAT, 2, '(2,)f4'), 
	int(GL_FLOAT_VEC3) : (glUniform3fv, GL_FLOAT, 3, '(3,)f4'), 
	int(GL_FLOAT_VEC4) : (glUniform4fv, GL_FLOAT, 4, '(4,)f4'), 
	int(GL_INT) : (glUniform1iv, GL_INT, 1, 'i4'), 
	int(GL_INT_VEC2) : (glUniform2iv, GL_INT, 2, '(2,)i4'), 
	int(GL_INT_VEC3) : (glUniform3iv, GL_INT, 3, '(3,)i4'), 
	int(GL_INT_VEC4) : (glUniform4iv, GL_INT, 4, '(4,)i4'), 
	int(GL_UNSIGNED_INT) : (glUniform1uiv, GL_UNSIGNED_INT, 1, 'u4'), 
	int(GL_UNSIGNED_INT_VEC2) : (glUniform2uiv, GL_UNSIGNED_INT, 2, '(2,)u4'), 
	int(GL_UNSIGNED_INT_VEC3) : (glUniform3uiv, GL_UNSIGNED_INT, 3, '(3,)u4'), 
	int(GL_UNSIGNED_INT_VEC4) : (glUniform4uiv, GL_UNSIGNED_INT, 4, '(4,)u4'), 
	int(GL_BOOL) : (glUniform1iv, GL_INT, 1, '?4'), 
	int(GL_BOOL_VEC2) : (glUniform2iv, GL_INT, 2, '(2,)?4'), 
	int(GL_BOOL_VEC3) : (glUniform3iv, GL_INT, 3, '(3,)?4'), 
	int(GL_BOOL_VEC4) : (glUniform4iv, GL_INT, 4, '(4,)?4'), 
	# unsure if bool is allowed as vertex attribute
	#	or if '(2,)?4' is even a valid dtype
	#	Though it's probably wasteful

	# int(GL_FLOAT_MAT2) : (glUniformMatrix2fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT3) : (glUniformMatrix3fv, GL_FLOAT, None), 
	int(GL_FLOAT_MAT4) : (glUniformMatrix4fv, GL_FLOAT, 16, '(4,4)f4'), 
	# int(GL_FLOAT_MAT2x3) : (glUniformMatrix2x3fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT2x4) : (glUniformMatrix2x4fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT3x2) : (glUniformMatrix3x2fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT3x4) : (glUniformMatrix3x4fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT4x2) : (glUniformMatrix4x2fv, GL_FLOAT, None), 
	# int(GL_FLOAT_MAT4x3) : (glUniformMatrix4x3fv, GL_FLOAT, None), 
	# unsure how the other matricies are implemented yet.

	# int(GL_DOUBLE) : glUniform1dv, 
	# int(GL_DOUBLE_VEC2) : glUniform2dv, 
	# int(GL_DOUBLE_VEC3) : glUniform3dv, 
	# int(GL_DOUBLE_VEC4) : glUniform4dv, 

	# int(GL_DOUBLE_MAT2) : glUniformMatrix2fv, 
	# int(GL_DOUBLE_MAT3) : glUniformMatrix3fv, 
	# int(GL_DOUBLE_MAT4) : glUniformMatrix4fv, 
	# int(GL_DOUBLE_MAT2x3) : glUniformMatrix2x3fv, 
	# int(GL_DOUBLE_MAT2x4) : glUniformMatrix2x4fv, 
	# int(GL_DOUBLE_MAT3x2) : glUniformMatrix3x2fv, 
	# int(GL_DOUBLE_MAT3x4) : glUniformMatrix3x4fv, 
	# int(GL_DOUBLE_MAT4x2) : glUniformMatrix4x2fv, 
	# int(GL_DOUBLE_MAT4x3) : glUniformMatrix4x3fv, 
}
# There are more, but I don't know yet what else is needed
# https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetActiveUniform.xhtml

VECTOR_TYPES = {
	'f' : [
		int(GL_FLOAT), 
		int(GL_FLOAT_VEC2), 
		int(GL_FLOAT_VEC3), 
		int(GL_FLOAT_VEC4)
	],
	'i' : [
		int(GL_INT), 
		int(GL_INT_VEC2), 
		int(GL_INT_VEC3), 
		int(GL_INT_VEC4)
	],
	'u' : [
		int(GL_UNSIGNED_INT), 
		int(GL_UNSIGNED_INT_VEC2), 
		int(GL_UNSIGNED_INT_VEC3), 
		int(GL_UNSIGNED_INT_VEC4)
	],
	'b' : [
		int(GL_BOOL), 
		int(GL_BOOL_VEC2), 
		int(GL_BOOL_VEC3), 
		int(GL_BOOL_VEC4)
	],
}

UNIFORM_TEXTURE_DICT = {
	int(GL_SAMPLER_1D) : (GL_TEXTURE_1D,),
	int(GL_SAMPLER_2D) : (GL_TEXTURE_2D,),
	int(GL_SAMPLER_3D) : (GL_TEXTURE_3D,),
	int(GL_SAMPLER_CUBE) : (GL_TEXTURE_CUBE_MAP,),
	int(GL_SAMPLER_1D_ARRAY) : (GL_TEXTURE_1D_ARRAY,),
	int(GL_SAMPLER_2D_ARRAY) : (GL_TEXTURE_2D_ARRAY,),
	int(GL_SAMPLER_2D_MULTISAMPLE) : (GL_TEXTURE_2D_MULTISAMPLE ,),
	int(GL_SAMPLER_2D_MULTISAMPLE_ARRAY) : (GL_TEXTURE_2D_MULTISAMPLE_ARRAY,),
	int(GL_SAMPLER_BUFFER) : (GL_TEXTURE_BUFFER,),
	int(GL_SAMPLER_2D_RECT) : (GL_TEXTURE_2D,),

	int(GL_SAMPLER_1D_SHADOW) : (GL_TEXTURE_1D,),
	int(GL_SAMPLER_2D_SHADOW) : (GL_TEXTURE_2D,),
	int(GL_SAMPLER_1D_ARRAY_SHADOW) : (GL_TEXTURE_1D_ARRAY,),
	int(GL_SAMPLER_2D_ARRAY_SHADOW) : (GL_TEXTURE_2D_ARRAY,),
	int(GL_SAMPLER_CUBE_SHADOW) : (GL_TEXTURE_CUBE_MAP,),
	int(GL_SAMPLER_2D_RECT_SHADOW) : (GL_TEXTURE_2D,),

	int(GL_INT_SAMPLER_1D) : (GL_TEXTURE_1D,),
	int(GL_INT_SAMPLER_2D) : (GL_TEXTURE_2D,),
	int(GL_INT_SAMPLER_3D) : (GL_TEXTURE_3D,),
	int(GL_INT_SAMPLER_CUBE) : (GL_TEXTURE_CUBE_MAP,),
	int(GL_INT_SAMPLER_1D_ARRAY) : (GL_TEXTURE_1D_ARRAY,),
	int(GL_INT_SAMPLER_2D_ARRAY) : (GL_TEXTURE_2D_ARRAY,),
	int(GL_INT_SAMPLER_2D_MULTISAMPLE) : (GL_TEXTURE_2D_MULTISAMPLE,),
	int(GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY) : (GL_TEXTURE_2D_MULTISAMPLE_ARRAY,),
	int(GL_INT_SAMPLER_BUFFER) : (GL_TEXTURE_BUFFER,),
	int(GL_INT_SAMPLER_2D_RECT) : (GL_TEXTURE_2D,),
	
	int(GL_UNSIGNED_INT_SAMPLER_1D) : (GL_TEXTURE_1D,),
	int(GL_UNSIGNED_INT_SAMPLER_2D) : (GL_TEXTURE_2D,),
	int(GL_UNSIGNED_INT_SAMPLER_3D) : (GL_TEXTURE_3D,),
	int(GL_UNSIGNED_INT_SAMPLER_CUBE) : (GL_TEXTURE_CUBE_MAP,),
	int(GL_UNSIGNED_INT_SAMPLER_1D_ARRAY) : (GL_TEXTURE_1D_ARRAY,),
	int(GL_UNSIGNED_INT_SAMPLER_2D_ARRAY) : (GL_TEXTURE_2D_ARRAY,),
	int(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE) : (GL_TEXTURE_2D_MULTISAMPLE,),
	int(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY) : (GL_TEXTURE_2D_MULTISAMPLE_ARRAY,),
	int(GL_UNSIGNED_INT_SAMPLER_BUFFER) : (GL_TEXTURE_BUFFER,),
	int(GL_UNSIGNED_INT_SAMPLER_2D_RECT) : (GL_TEXTURE_2D,),
}

UNIFORM_SYMBOL_DICT = {
	'float' : int(GL_FLOAT),
	'vec2' : int(GL_FLOAT_VEC2),
	'vec3' : int(GL_FLOAT_VEC3),
	'vec4' : int(GL_FLOAT_VEC4),
	'int' : int(GL_INT),
	'ivec2' : int(GL_INT_VEC2),
	'ivec3' : int(GL_INT_VEC3),
	'ivec4' : int(GL_INT_VEC4),
	'uint' : int(GL_UNSIGNED_INT),
	'uvec2' : int(GL_UNSIGNED_INT_VEC2),
	'uvec3' : int(GL_UNSIGNED_INT_VEC3),
	'uvec4' : int(GL_UNSIGNED_INT_VEC4),
	'bool' : int(GL_BOOL),
	'bvec2' : int(GL_BOOL_VEC2),
	'bvec3' : int(GL_BOOL_VEC3),
	'bvec4' : int(GL_BOOL_VEC4),
	# 'mat2' : int(GL_FLOAT_MAT2),
	# 'mat3' : int(GL_FLOAT_MAT3),
	'mat4' : int(GL_FLOAT_MAT4),
	# 'mat2x3' : int(GL_FLOAT_MAT2x3),
	# 'mat2x4' : int(GL_FLOAT_MAT2x4),
	# 'mat3x2' : int(GL_FLOAT_MAT3x2),
	# 'mat3x4' : int(GL_FLOAT_MAT3x4),
	# 'mat4x2' : int(GL_FLOAT_MAT4x2),
	# 'mat4x3' : int(GL_FLOAT_MAT4x3),

	'sampler1D' : int(GL_SAMPLER_1D),
	'sampler2D' : int(GL_SAMPLER_2D),
	'sampler3D' : int(GL_SAMPLER_3D),
	'samplerCube' : int(GL_SAMPLER_CUBE),
	'sampler1DShadow' : int(GL_SAMPLER_1D_SHADOW),
	'sampler2DShadow' : int(GL_SAMPLER_2D_SHADOW),
	'sampler1DArray' : int(GL_SAMPLER_1D_ARRAY),
	'sampler2DArray' : int(GL_SAMPLER_2D_ARRAY),
	'sampler1DArrayShadow' : int(GL_SAMPLER_1D_ARRAY_SHADOW),
	'sampler2DArrayShadow' : int(GL_SAMPLER_2D_ARRAY_SHADOW),
	'sampler2DMS' : int(GL_SAMPLER_2D_MULTISAMPLE),
	'sampler2DMSArray' : int(GL_SAMPLER_2D_MULTISAMPLE_ARRAY),
	'samplerCubeShadow' : int(GL_SAMPLER_CUBE_SHADOW),
	'samplerBuffer' : int(GL_SAMPLER_BUFFER),
	'sampler2DRect' : int(GL_SAMPLER_2D_RECT),
	'sampler2DRectShadow' : int(GL_SAMPLER_2D_RECT_SHADOW),
	'isampler1D' : int(GL_INT_SAMPLER_1D),
	'isampler2D' : int(GL_INT_SAMPLER_2D),
	'isampler3D' : int(GL_INT_SAMPLER_3D),
	'isamplerCube' : int(GL_INT_SAMPLER_CUBE),
	'isampler1DArray' : int(GL_INT_SAMPLER_1D_ARRAY),
	'isampler2DArray' : int(GL_INT_SAMPLER_2D_ARRAY),
	'isampler2DMS' : int(GL_INT_SAMPLER_2D_MULTISAMPLE),
	'isampler2DMSArray' : int(GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
	'isamplerBuffer' : int(GL_INT_SAMPLER_BUFFER),
	'isampler2DRect' : int(GL_INT_SAMPLER_2D_RECT),
	'usampler1D' : int(GL_UNSIGNED_INT_SAMPLER_1D),
	'usampler2D' : int(GL_UNSIGNED_INT_SAMPLER_2D),
	'usampler3D' : int(GL_UNSIGNED_INT_SAMPLER_3D),
	'usamplerCube' : int(GL_UNSIGNED_INT_SAMPLER_CUBE),
	'usampler2DArray' : int(GL_UNSIGNED_INT_SAMPLER_1D_ARRAY),
	'usampler2DArray' : int(GL_UNSIGNED_INT_SAMPLER_2D_ARRAY),
	'usampler2DMS' : int(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE),
	'usampler2DMSArray' : int(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY),
	'usamplerBuffer' : int(GL_UNSIGNED_INT_SAMPLER_BUFFER),
	'usampler2DRect' : int(GL_UNSIGNED_INT_SAMPLER_2D_RECT),

	# Currently unsupported due currently being restricted to version 3.3.

	# 'double' : int(GL_DOUBLE),
	# 'dvec2' : int(GL_DOUBLE_VEC2),
	# 'dvec3' : int(GL_DOUBLE_VEC3),
	# 'dvec4' : int(GL_DOUBLE_VEC4),

	# 'dmat2' : int(GL_DOUBLE_MAT2),
	# 'dmat3' : int(GL_DOUBLE_MAT3),
	# 'dmat4' : int(GL_DOUBLE_MAT4),
	# 'dmat2x3' : int(GL_DOUBLE_MAT2x3),
	# 'dmat2x4' : int(GL_DOUBLE_MAT2x4),
	# 'dmat3x2' : int(GL_DOUBLE_MAT3x2),
	# 'dmat3x4' : int(GL_DOUBLE_MAT3x4),
	# 'dmat4x2' : int(GL_DOUBLE_MAT4x2),
	# 'dmat4x3' : int(GL_DOUBLE_MAT4x3),

	# 'image1D' : int(GL_IMAGE_1D),
	# 'image2D' : int(GL_IMAGE_2D),
	# 'image3D' : int(GL_IMAGE_3D),
	# 'image2DRect' : int(GL_IMAGE_2D_RECT),
	# 'imageCube' : int(GL_IMAGE_CUBE),
	# 'imageBuffer' : int(GL_IMAGE_BUFFER),
	# 'image1DArray' : int(GL_IMAGE_1D_ARRAY),
	# 'image2DArray' : int(GL_IMAGE_2D_ARRAY),
	# 'image2DMS' : int(GL_IMAGE_2D_MULTISAMPLE),
	# 'image2DMSArray' : int(GL_IMAGE_2D_MULTISAMPLE_ARRAY),
	# 'iimage1D' : int(GL_INT_IMAGE_1D),
	# 'iimage2D' : int(GL_INT_IMAGE_2D),
	# 'iimage3D' : int(GL_INT_IMAGE_3D),
	# 'iimage2DRect' : int(GL_INT_IMAGE_2D_RECT),
	# 'iimageCube' : int(GL_INT_IMAGE_CUBE),
	# 'iimageBuffer' : int(GL_INT_IMAGE_BUFFER),
	# 'iimage1DArray' : int(GL_INT_IMAGE_1D_ARRAY),
	# 'iimage2DArray' : int(GL_INT_IMAGE_2D_ARRAY),
	# 'iimage2DMS' : int(GL_INT_IMAGE_2D_MULTISAMPLE),
	# 'iimage2DMSArray' : int(GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY),
	# 'uimage1D' : int(GL_UNSIGNED_INT_IMAGE_1D),
	# 'uimage2D' : int(GL_UNSIGNED_INT_IMAGE_2D),
	# 'uimage3D' : int(GL_UNSIGNED_INT_IMAGE_3D),
	# 'uimage2DRect' : int(GL_UNSIGNED_INT_IMAGE_2D_RECT),
	# 'uimageCube' : int(GL_UNSIGNED_INT_IMAGE_CUBE),
	# 'uimageBuffer' : int(GL_UNSIGNED_INT_IMAGE_BUFFER),
	# 'uimage1DArray' : int(GL_UNSIGNED_INT_IMAGE_1D_ARRAY),
	# 'uimage2DArray' : int(GL_UNSIGNED_INT_IMAGE_2D_ARRAY),
	# 'uimage2DMS' : int(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE),
	# 'uimage2DMSArray' : int(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY),
	# 'atomic_uint' : int(GL_UNSIGNED_INT_ATOMIC_COUNTER),
}